version: '3.9'

services:
  pulsar:
    image: apachepulsar/pulsar:3.2.0
    container_name: pulsar
    ports:
      - "6650:6650"    # puerto binario para clientes
      - "8080:8080"    # puerto HTTP (admin)
    command: >
      bin/pulsar standalone
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/admin/v2/brokers/health"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - pulsar-net

  proveedor:
    image: proveedor:latest
    container_name: proveedor
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - pulsar
    environment:
      - ASPNETCORE_URLS=http://+:8080
      - PULSAR_SERVICE_URL=pulsar://pulsar:6650
    ports:
      - "5000:8080"
    networks:
      - pulsar-net

networks:
  pulsar-net:
    driver: bridge
